### ISSUE TITLE
Prepare milestone for release & deployment

### ISSUE THREAD

**Issue by varyndev** [VarynInc/varyn#159]
#### Enginesis

- [x] database backed up
- [x] schema diff updates -q, LIVE
- [x] procedures updated -q, LIVE
- [x] database backed up then loaded -l
- [x] procedures reloaded -l
- [x] unit tests pass -l
- [x] Enginesis PHP, JS sdk synced, updated -q, LIVE
- [x] code deployed -q, LIVE
- [x] unit tests pass -q, LIVE
- [x] version up procedures.sql, enginesis.php, enginesis.js, version.php

#### Varyn

- [x] Enginesis PHP, JS sdk synced, updated -q, LIVE
- [x] code deployed -q, LIVE

**Comment by DarkMatters** [comment]
Deployed on 8/12 BUT we did not finish the SSOs. Everything else for this milestone appears to be complete and tested.
