### ISSUE TITLE
Media upload service

### ISSUE THREAD

**Issue by DarkMatters** [VarynInc/varyn#185]
Media upload service to allow uploading of media files
 + Images
 + Video
 + Audio
 + ZIP archives, such as for games

- [x] Service request service, end point to request an upload
  + [x] File name
  + [x] file size
  + [x] content type
  + [x] service object parameters (e.g. game-id, conference-id, avatar, site-id, etc) so we know what this file is associated with
  + [x] session token
  + [x] respond with end-point URL, upload token (one-time authorization to match parameters), final path

- [x] Service follow-up
  + [x] provide one-time authorization token
  + [x] provide file data
  + [x] respond with ok/error

**Comment by DarkMatters** [comment]
started /procs/asset.php

**Comment by DarkMatters** [comment]
See 
+ http://php.net/manual/en/features.file-upload.php
+ http://php.net/manual/en/function.move-uploaded-file.php
+ http://php.net/manual/en/reserved.variables.files.php
+ njmasters /procs/uploadphoto.php

**Comment by DarkMatters** [comment]
### TODO:

1. how to specify the required parameters for the type of upload (conf id, game-id, etc.)
2. how to determine the file name. Some use the MD5 technique. Some (avatar assets) cannot

**Comment by DarkMatters** [comment]
Everything stated above is completed. In /procs/asset.php. Remaining tasks:

+ [ ] check expiration of request
+ [ ] solve duplicate key issue. when uploading the same file we get the same token and it already exists it fails. Need a solution for this.
+ [ ] response shows file path, change it to URI to final asset
+ [ ] in file upload tester (fileuploader.php) change state of button to be `Request token` first, then change button to `Upload file`
+ [ ] in file upload tester (fileuploader.php) if upload fails, reset token so re-upload doesn't fail

**Comment by varyndev** [comment]
Duplicate key issue is addressed by using the replace parameter to replace a matching request.
