### ISSUE TITLE
Release Reset password milestone release checklist

### ISSUE THREAD

**Issue by varyndev** [VarynInc/varyn#85]
### Prep for release

- [x] procedures updated -q, LIVE
- [x] schema diff updates -q, LIVE
- [x] Enginesis PHP, JS sdk updated -q, LIVE
- [x] code deployed -q, LIVE
- [x] unit tests pass

- [x] Test create account
- [x] Test change password
- [x] Test forgot password

**Comment by varyndev** [comment]
fully deployed 3/18/2017, only about 4 months late!
