### ISSUE TITLE
Conferences: Consider MVP

### ISSUE THREAD

**Issue by varyndev** [VarynInc/varyn#91]
We are adding our own conferencing functionality we should consider why we need WP and what functionality it provides that our system is lacking.

Further development on our own functionality helps move it forward vs. investing time and effort into WP. Our conference system is a much different concept than a blog, and therefore WP doesn't address the true requirement. We are going for a group collaboration system that emphasizes groups of people working together and contributing as a group toward a specific goal, and not a one-way broadcast.

### To-do in this ticket:
+ [x] MVP Conference functionality
+ [x] What does WP provide that we need yet we don't have
  - markdown editor
  - Handling of media files, uploading, updating
  - short codes
  - editor
  - comment on topics
  - replies to comments

+ [x] Conference system design
    - [x] Conference
    - [x] Membership
    - [x] Conference Topics
    - [x] Comments
    - [x] Comment replies
    - [x] Comment tag index
    - [x] Comment seen - track comments read by member

+ [x] Implementation roadmap

### Initial MVP functionality:

Review schema, procedures, API for 

- [x] Conference
  + [x] Create
  + [x] Update
  + [x] Membership-list
  + [x] User-assign
  + [x] User-remove
  + [x] Get
  + [x] List
  + [x] Find (keyword and title search)
  + [x] read & unread comments, replies
  + [x] ConferenceMemberStatusList (Show user status in all confs)
- [x] Conference Topic
  + [x] Topic-create
  + [x] Topic-update
  + [x] Topic-list
  + [x] Topic-get
  + [x] Topic-delete
  + [x] Conference topic feed (topics since date in RSS format)
- [x] Conference Comment
  + [x] Comment-create
  + [x] Comment-update
  + [x] Comment-list
  + [x] Comment-get
  + [x] Comment-delete
  + [x] Comment-reply-create
  + [x] Comment-reply-update
  + [x] Comment-reply-list
  + [x] Conference feed (comments since date in RSS format)

- [x] Roles and privileges - for now, very simple role-based, improve later.
- [x] Scratchpad - basic edit and save
- [x] User
- [x] Group
- [x] Notification
- [x] Collections
- [x] Media
   + [x] file upload
   + [x] file reference
   + [x] file management (orphaned, delete)

![32x32](https://user-images.githubusercontent.com/5832539/31059036-bff1d838-a6b2-11e7-8c02-7410c55d2274.png)

**Comment by varyndev** [comment]
Review procedures for 
- [ ] Conference
- [ ] User
- [ ] Group
- [ ] Roles and privileges

**Comment by DarkMatters** [comment]
A few things are not done but they are not required for the MVP. The basic backend is in place. Next step is to build the UI and update backend as required. Making separate issues for all that work.
